variables:
  JEKYLL_ENV: production
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "3"

pages:
  stage: deploy
  script:
    - exec jekyll build -d public
  artifacts:
    paths:
      - public
  tags:
    - jekyll
  only:
    - gh-pages
